-- Business Question 1 : What is the overall revenue and profit generated by the business?

SELECT
	ROUND(SUM(sales),2) AS total_revenue,
    ROUND(SUM(profit),2) AS total_profit
FROM
	superstore_sales;
    
-- Business Question 2 : Which product categories contribute the most revenue and profit?

SELECT 
	category,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(profit),2) AS profit
FROM
	superstore_sales
GROUP BY 
	category
ORDER BY 
	revenue DESC;

-- Business Question 3 : Which categories generate the highest profit margin?

SELECT
    category,
    ROUND(AVG(profit_margin),2) AS avg_profit_margin_pct
FROM 
	superstore_sales
GROUP BY 
	category
ORDER BY 
	avg_profit_margin_pct DESC;

-- Business Question 4 : Which sub-categories generate high revenue but low profit margins?

SELECT
    sub_category,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(AVG(profit_margin),2) AS avg_profit_margin_pct
FROM 
	superstore_sales
GROUP BY 
	sub_category
ORDER BY 
	revenue DESC;
    
-- PRODUCT PERFORMANCE ANALYSIS
    
-- Business Question 5 : Top 10 Products Generating Highest Revenue

SELECT 
    product_name, ROUND(SUM(sales), 2) AS revenue
FROM
    superstore_sales
GROUP BY 
	product_name
ORDER BY 
	revenue DESC
LIMIT 10;

-- Business Question 6 : Top 10 Products Generating Highest Profit

SELECT
    product_name,
    ROUND(SUM(profit),2) AS profit
FROM 
	superstore_sales
GROUP BY
	product_name
ORDER BY 
	profit DESC
LIMIT 10;

-- Business Question 7 : Products Generating Highest Losses

SELECT
    product_name,
    ROUND(SUM(profit),2) AS loss
FROM 
	superstore_sales
GROUP BY 
	product_name
HAVING 
	SUM(profit) < 0
ORDER BY 
	loss
LIMIT 10;

-- Business Question 8 : Which products rank among the top 5 profit-generating products within each category?

WITH product_profit AS (
    SELECT
        category,
        product_name,
        ROUND(SUM(profit),2) AS total_profit,
        RANK() OVER(PARTITION BY category ORDER BY SUM(profit) DESC) AS profit_rank
    FROM 
		superstore_sales
    GROUP BY 
		category, product_name
)

SELECT
    category,
    product_name,
    total_profit,
    profit_rank
FROM 
	product_profit
WHERE 
	profit_rank <= 5;

-- CUSTOMER ANALYSIS

-- Business Question 9 : Which customer segments contribute the most revenue and profit?

SELECT
    segment,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(profit),2) AS profit
FROM
	superstore_sales
GROUP BY 
	segment
ORDER BY
	revenue DESC;

-- Business Question 10 : What percentage of total revenue is contributed by each customer segment?

SELECT
    segment,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(
        SUM(sales) * 100 /
        SUM(SUM(sales)) OVER(),
        2
    ) AS revenue_contribution_pct
FROM 
	superstore_sales
GROUP BY 
	segment;

-- Business Question 11 :Which customer segments generate the highest profit margins?

SELECT
    segment,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(profit),2) AS profit,
    ROUND(AVG(profit_margin),2) AS avg_profit_margin_pct
FROM 
	superstore_sales
GROUP BY 
	segment
ORDER BY 
	avg_profit_margin_pct DESC;

-- Business Question 12 : Which customers generate the highest revenue?

SELECT
    customer_name,
    ROUND(SUM(sales),2) AS revenue
FROM 
	superstore_sales
GROUP BY 
	customer_name
ORDER BY 
	revenue DESC
LIMIT 10;

-- Business Question 13 : Who is the highest revenue-generating customer within each segment?
    
WITH customer_sales AS (
    SELECT
        segment,
        customer_name,
        ROUND(SUM(sales),2) AS revenue,
        ROW_NUMBER() OVER(PARTITION BY segment ORDER BY SUM(sales) DESC) AS rn
    FROM 
		superstore_sales
    GROUP BY 
		segment, 
        customer_name
)
SELECT *
FROM 
	customer_sales
WHERE
	rn = 1;
    
-- Business Question 14 : Which customers are generating overall losses for the business?

SELECT
    customer_name,
    total_profit
FROM (
    SELECT
        customer_name,
        SUM(profit) AS total_profit
    FROM 
		superstore_sales
    GROUP BY 
		customer_name
) t
WHERE 
	total_profit < 0
ORDER BY 
	total_profit;

-- SALES TREND ANALYSIS    

-- Business Question 15 : Monthly Revenue Trend

SELECT
    order_year,
    order_month,
    ROUND(SUM(sales),2) AS revenue
FROM 
	superstore_sales
GROUP BY 
	order_year, 
    order_month
ORDER BY 
	order_year, 
    order_month;
    
-- Business Question 16 : Year-Over-Year Growth

WITH yearly_sales AS (
    SELECT
        order_year,
        SUM(sales) AS revenue
    FROM 
		superstore_sales
    GROUP BY 
		order_year
)
SELECT
    order_year,
    revenue,
    LAG(revenue) OVER (ORDER BY order_year) AS previous_year_revenue,
    ROUND((revenue - LAG(revenue) OVER (ORDER BY order_year)) * 100.0 / LAG(revenue) OVER (ORDER BY order_year),2
    ) AS yoy_growth_pct
FROM 
	yearly_sales;

-- GEOGRAPHICAL ANALYSIS

-- Business Question 17 : Which states generate the highest profit margin?

SELECT
    state,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(profit),2) AS profit,
    ROUND(AVG(profit_margin),2) AS avg_profit_margin_pct
FROM 
	superstore_sales
GROUP BY 
	state
ORDER BY 
	avg_profit_margin_pct DESC;
    

-- OPERATIONAL ANALYSIS

-- Business Question 18 : How does Discount affect Profitability?

SELECT
    discount,
    COUNT(*) AS total_orders,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(AVG(profit),2) AS avg_profit
FROM 
	superstore_sales
GROUP BY 
	discount
ORDER BY 
	discount;

-- Business Question 19 : Shipping Bucket Performance

SELECT
    shipping_bucket,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(profit),2) AS profit
FROM 
	superstore_sales
GROUP BY 
	shipping_bucket
ORDER BY 
	revenue DESC;












